# AUTOGENERATED! DO NOT EDIT! File to edit: 04_NN.ipynb (unless otherwise specified).

__all__ = ['learnPosterior']

# Cell
import xgboost as xgb

def learnPosterior(xTrain,yTrain,
                   params={'max_depth':2, 'eta':1, 'objective':'binary:logistic' },
                   num_round=2):
    dtrain = xgb.DMatrix(xTrain,yTrain)
    model = xgb.train(params, dtrain, num_round)
    return model